branches:
  - develop

language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

env:
  - SYMFONY_VERSION="~2.8.12" DB=mysql

git:
    submodules: false

before_script:
  - mysql -e 'CREATE DATABASE `zstu_xyb_test` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci'
  - cp app/config/parameters_test.yml.dist app/config/parameters_test.yml
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - mkdir web/files

script:
  - phpunit -c app/

cache:
  directories:
    - $HOME/.composer/cache