branches:
  - master
  - feature/x8

language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

env:
  - SYMFONY_VERSION="~2.8.12" DB=mysql

git:
    submodules: false

before_install:
  - echo -e "Host gitlab.howzhi.net:4422\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git submodule update --init --recursive

before_script:
  - mysql -e 'CREATE DATABASE `edusoho-test` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci'
  - mysql -u root -e "CREATE USER 'tester'@'localhost' IDENTIFIED BY 'tester'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'tester'@'localhost'"
  - cp app/config/parameters_test.yml.dist app/config/parameters_test.yml
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - mkdir web/files
  - touch app/config/routing_plugins.yml

script:
  - phpunit -c app/

cache:
  directories:
    - $HOME/.composer/cache