parameters:
    biz: 
        debug: "%kernel.debug%"
        db.options:
            dbname: "%database_name%"
            user: "%database_user%"
            password: "%database_password%"
            host: "%database_host%"
            port: "%database_port%"
            driver: pdo_mysql
            charset: UTF8
        cache_directory: "%kernel.root_dir%/../var/cache"
        tmp_directory: "%kernel.root_dir%/../var/tmp"
        log_directory: "%kernel.root_dir%/../var/logs"
        upload.public_directory: "%kernel.root_dir%/../web/files"
        upload.public_url_path: "/files"
        upload.private_directory: "%kernel.root_dir%/../var/data/private_files"
        disk.local_directory: "%kernel.root_dir%/../var/data/udisk"