userRole:
    ROLE_USER: 用户
    ROLE_ADMIN: 管理员
    ROLE_SUPER_ADMIN: 超级管理员
userKeyWordType:
    username: 用户名
    nickname: 昵称
    email: 邮件地址
    loginIp: 登录IP
expressType:
    1: 小包裹
    2: 中包裹
    3: 大包裹
expressStatus:
    1: 待认领
    2: 被认领
    3: 已送达
    4: 已确认  
expressKeyWordType:
    nickname: 发布人昵称
    title: 标题
goodsStatus:
    1: 未发布
    2: 已发布
    3: 已关闭
goodsKeyWordType:
    nickname: 发布人昵称
    title: 标题
groupStatus:
    open: 开启
    close: 关闭
threadStatus:
    open: 开启
    close: 关闭
threadType:
    isStick: 置顶
    isElite: 加精
log-level:
    info: '提示'
    warning: '警告'
    danger: '危险'
    error: '错误'
log-module:
    system: '系统'
    goods: '旧货交易'
    thread: '话题管理'
    group: '小组管理'
    category: '分类管理'
    user: '用户管理'
    crontab: '定时任务'