admin_dashboard:
  path:      /
  defaults:  { _controller: AppBundle:Admin/Default:index }

admin_user:
  path:      /user
  defaults:  { _controller: AppBundle:Admin/User:index }

admin_user_show:
  path:      /user/{id}/show
  defaults:  { _controller: AppBundle:Admin/User:show }
