homepage:
  path:      /
  defaults:  { _controller: AppBundle:Default:index }

login:
  path: /login
  defaults:  { _controller: AppBundle:Login:index }

login_check:
  path: /login_check

logout:
  path: /logout

file_upload:
  path:      /file/upload
  defaults:  { _controller: AppBundle:File:upload }

file_img_crop:
  path:      /file/crop
  defaults:  { _controller: AppBundle:File:crop }

app_goods:
  path:      /goods
  defaults:  { _controller: AppBundle:Goods:index }

app_goods_show:
  path:      /goods/{id}
  defaults:  { _controller: AppBundle:Goods:goods }

default_crontab:
    path:  /default/crontab
    defaults: { _controller: AppBundle:Default:crontab }