admin_dashboard:
  path:      /
  defaults:  { _controller: AppBundle:Admin/Default:index }

admin_user:
  path:      /user
  defaults:  { _controller: AppBundle:Admin/User:index }

admin_user_show:
  path:      /user/{id}/show
  defaults:  { _controller: AppBundle:Admin/User:show }

admin_user_create:
  path:      /user/create
  defaults:  { _controller: AppBundle:Admin/User:create }

admin_user_create_username_check:
  path:      /user/create/check/username
  defaults:  { _controller: AppBundle:Admin/User:checkUsername }

admin_user_create_email_check:
  path:      /user/create/chcek/email
  defaults:  { _controller: AppBundle:Admin/User:checkEmail }

admin_express:
  path:      /express
  defaults:  { _controller: AppBundle:Admin/Express:index }

admin_express_show:
  path:      /express/{id}/show
  defaults:  { _controller: AppBundle:Admin/Express:show }