admin_dashboard:
  path:      /
  defaults:  { _controller: AppBundle:Admin/Default:index }

admin_user:
  path:      /user
  defaults:  { _controller: AppBundle:Admin/User:index }

admin_user_show:
  path:      /user/{id}/show
  defaults:  { _controller: AppBundle:Admin/User:show }

admin_user_create:
  path:      /user/create
  defaults:  { _controller: AppBundle:Admin/User:create }

admin_user_create_username_check:
  path:      /user/create/check/username
  defaults:  { _controller: AppBundle:Admin/User:checkUsername }

admin_user_create_email_check:
  path:      /user/create/chcek/email
  defaults:  { _controller: AppBundle:Admin/User:checkEmail }

admin_user_roles:
  path:      /user/{id}/roles
  defaults:  { _controller: AppBundle:Admin/User:roles }

admin_user_lock:
  path:      /user/{id}/lock
  defaults:  { _controller: AppBundle:Admin/User:lock }

admin_user_unlock:
  path:      /user/{id}/unlock
  defaults:  { _controller: AppBundle:Admin/User:unlock }

admin_express:
  path:      /express
  defaults:  { _controller: AppBundle:Admin/Express:index }

admin_express_show:
  path:      /express/{id}/show
  defaults:  { _controller: AppBundle:Admin/Express:show }

admin_goods:
  path:      /goods
  defaults:  { _controller: AppBundle:Admin/Goods:index }

admin_goods_show:
  path:      /goods/{id}/show
  defaults:  { _controller: AppBundle:Admin/Goods:show }

admin_goods_publish:
  path:      /goods/{id}/publish
  defaults:  { _controller: AppBundle:Admin/Goods:publish }
  requirements:
    _method: POST

admin_goods_close:
  path:      /goods/{id}/close
  defaults:  { _controller: AppBundle:Admin/Goods:close }
  requirements:
    _method: POST

admin_goods_category:
  path:  /goods/category
  defaults: { _controller: AppBundle:Admin/Goods:category }

admin_goods_category_create:
  path:  /goods/category/create
  defaults: { _controller: AppBundle:Admin/Goods:createCategory }

admin_goods_category_edit:
  path:  /goods/category/{id}/edit
  defaults: { _controller: AppBundle:Admin/Goods:editCategory }

admin_goods_category_delete:
  path:  /goods/category/{id}/delete
  defaults: { _controller: AppBundle:Admin/Goods:deleteCategory }

admin_goods_category_checkcode:
  path:  /goods/category/checkcode
  defaults: { _controller: AppBundle:Admin/Goods:checkcode }

admin_group:
  path:      /group
  defaults:  { _controller: AppBundle:Admin/Group:group }

admin_group_open:
  path:      /group/{id}/open
  defaults:  { _controller: AppBundle:Admin/Group:open }
  requirements:
    _method: POST

admin_group_close:
  path:      /group/{id}/close
  defaults:  { _controller: AppBundle:Admin/Group:close }
  requirements:
    _method: POST

admin_group_transfer:
  path:      /group/{id}/transfer
  defaults:  { _controller: AppBundle:Admin/Group:transfer }

admin_group_checkuser:
  path:      /group/checkuser
  defaults:  { _controller: AppBundle:Admin/Group:checkUser }  

admin_thread:
  path:      /thread
  defaults:  { _controller: AppBundle:Admin/Group:thread }

admin_thread_delete:
  path:      /thread/{id}/delete
  defaults:  { _controller: AppBundle:Admin/Group:deleteThread }
  requirements:
    _method: POST

admin_thread_open:
  path:      /thread/{id}/open
  defaults:  { _controller: AppBundle:Admin/Group:openThread}
  requirements:
    _method: POST 

admin_thread_close:
  path:      /thread/{id}/close
  defaults:  { _controller: AppBundle:Admin/Group:closeThread }
  requirements:
    _method: POST

admin_thread_cancel_stick:
  path:      /thread/{id}/cancelStick
  defaults:  { _controller: AppBundle:Admin/Group:cancelStick }
  requirements:
    _method: POST

admin_thread_set_stick:
  path:      /thread/{id}/setStick
  defaults:  { _controller: AppBundle:Admin/Group:setStick }
  requirements:
    _method: POST

admin_thread_cancel_elite:
  path:      /thread/{id}/cancelElite
  defaults:  { _controller: AppBundle:Admin/Group:cancelElite }
  requirements:
    _method: POST

admin_thread_set_elite:
  path:      /thread/{id}/setElite
  defaults:  { _controller: AppBundle:Admin/Group:setElite }
  requirements:
    _method: POST

admin_setting_site:
  path:  /setting/site
  defaults: { _controller: AppBundle:Admin/Setting:site }

admin_log_modal:
  path:      /log
  defaults:  { _controller: AppBundle:Admin/Log:showModal }
  requirements:
    _method: GET

admin_system_log_list:
  path:      /system/log
  defaults:  { _controller: AppBundle:Admin/Log:showList }

admin_log_info_modal:
  path:      /system/log/{logId}
  defaults:  { _controller: AppBundle:Admin/Log:showInfoModal }
  requirements:
    _method: GET
    logId: \d+
