admin_dashboard:
  path:      /
  defaults:  { _controller: AppBundle:Admin/Default:index }

admin_user:
  path:      /user
  defaults:  { _controller: AppBundle:Admin/User:index }

admin_user_show:
  path:      /user/{id}/show
  defaults:  { _controller: AppBundle:Admin/User:show }

admin_user_create:
  path:      /user/create
  defaults:  { _controller: AppBundle:Admin/User:create }

admin_user_create_username_check:
  path:      /user/create/check/username
  defaults:  { _controller: AppBundle:Admin/User:checkUsername }

admin_user_create_email_check:
  path:      /user/create/chcek/email
  defaults:  { _controller: AppBundle:Admin/User:checkEmail }

admin_user_roles:
  path:      /user/{id}/roles
  defaults:  { _controller: AppBundle:Admin/User:roles }

admin_user_lock:
  path:      /user/{id}/lock
  defaults:  { _controller: AppBundle:Admin/User:lock }

admin_user_unlock:
  path:      /user/{id}/unlock
  defaults:  { _controller: AppBundle:Admin/User:unlock }

admin_express:
  path:      /express
  defaults:  { _controller: AppBundle:Admin/Express:index }

admin_express_show:
  path:      /express/{id}/show
  defaults:  { _controller: AppBundle:Admin/Express:show }

admin_goods:
  path:      /goods
  defaults:  { _controller: AppBundle:Admin/Goods:index }

admin_goods_show:
  path:      /goods/{id}/show
  defaults:  { _controller: AppBundle:Admin/Goods:show }

admin_goods_publish:
  path:      /goods/{id}/publish
  defaults:  { _controller: AppBundle:Admin/Goods:publish }
  requirements:
    _method: POST

admin_goods_close:
  path:      /goods/{id}/close
  defaults:  { _controller: AppBundle:Admin/Goods:close }
  requirements:
    _method: POST

admin_group:
  path:      /group
  defaults:  { _controller: AppBundle:Admin/Group:group }

admin_group_open:
  path:      /group/{id}/open
  defaults:  { _controller: AppBundle:Admin/Group:open }
  requirements:
    _method: POST

admin_group_close:
  path:      /group/{id}/close
  defaults:  { _controller: AppBundle:Admin/Group:close }
  requirements:
    _method: POST

admin_group_transfer:
  path:      /group/{id}/transfer
  defaults:  { _controller: AppBundle:Admin/Group:transfer }

admin_group_checkuser:
  path:      /group/checkuser
  defaults:  { _controller: AppBundle:Admin/Group:checkUser }  

admin_group_thread:
  path:      /group/thread
  defaults:  { _controller: AppBundle:Admin/Group:thread }